### ISSUE TITLE
Nit: Enhancement to `settings.local.php` comment semantics

### ISSUE THREAD

**Issue by richardgaunt** [drevops/scaffold#1246]
https://github.com/drevops/scaffold/blob/develop/web/sites/default/default.settings.local.php#L18

Current:
```
// Disable CSS files aggregation.
$config['system.performance']['css']['preprocess'] = FALSE;
```

```
// Set to FALSE to disable CSS aggregation.
$config['system.performance']['css']['preprocess'] = FALSE;
```

And the same for JS aggregation, it confuses me everytime I look at it as I always have the urge double check it for correctness - also if a user changes it for debugging then the comment is no longer correct.

**Comment by AlexSkrypnyk** [comment]
The comments are correct - the code already has a value set to `FALSE` meaning that the code below already does what the comment above says.

Updating it to what you suggesting reads like a duplication - the value is already set to `FALSE`.
