### ISSUE TITLE
Allow to configure site configuration location via environment variable

### ISSUE THREAD

**Issue by richardgaunt** [drevops/scaffold#1328]
Currently, `config_sync_directory` is hardcoded into `settings.php`. 

For testing installations from profile and module configuration it is handy to be able to change the configuration directory.

Propose adding a `DRUPAL_CONFIG_DIRECTORY` variable to provide overrideable settings at:
https://github.com/drevops/scaffold/blob/develop/web/sites/default/settings.php#L61

**Comment by AlexSkrypnyk** [comment]
`DRUPAL_CONFIG_PATH`
