### ISSUE TITLE
Add linter for behat features

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#505]

**Comment by alexdesignworks** [comment]
Currently, only https://github.com/vsiakka/gherkin-lint NPM-based linter exists, which is not the best option for PHP-based project. Putting this on the back-burner for now.

**Comment by AlexSkrypnyk** [comment]
This is still relevant.

**Comment by AlexSkrypnyk** [comment]
https://github.com/dantleech/gherkin-lint-php
