### ISSUE TITLE
chore: Add standalone tests for deployment scripts

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/scaffold#736]
Currently, tests are added as a part of deployment workflow.

We need to create separate unit tests with mocked binaries to test all variations.

Note that Lagoon deployment scripts are already using mocks.

**Comment by richardgaunt** [comment]
> Currently, tests are added as a part of deployment workflow.
> 
> We need to create separate unit tests with mocked binaries to test all variations.
> 
> Note that Lagoon deployment scripts are already using mocks.

https://github.com/drevops/bats-helpers/pull/44

This PR will make it possible to mock out the lagoon steps with the step runner and in turn I am sure it will help with the other mocks

**Comment by AlexSkrypnyk** [comment]
@richardgaunt 
Thank you for contributing that PR. I'm not sure I understand how exactly it would help. 

Currently, the assertions within steps replicate exact command calls with all args and we want to assert for that. We do not want to assert for some unpredictable args as this may change the behaviour of the command being mocked, which would defeat the whole purpose of the test.
